In [39]:
import numpy as np
from sklearn.model_selection import StratifiedKFold


X = np.array([[0, 0], [1, 1], [2, 2], [3, 3], [4, 4], [5, 5], [6, 6], [7, 7]])
y = np.array([1, 1, 1, 1, 0, 0, 0, 0])

#notes: the stratification is based on the y_labels; 
# say if have y[1,2,3,4,5,6,7,8] the model will run into issues as there isn't a way to stratify
# I do NOT fully understand this

print("X:\n", X)
print("y:\n", np.matrix(y).T, "\n")

fold_by_2 = StratifiedKFold(n_splits = 2).split(X, y)  # this output is some kind of object not visualizable

fold_count = 1
for rows_for_training, rows_for_testing in fold_by_2:
    
    print("=====================")
    
    print("This is the #", fold_count, "fold of this stratification\n" )
    print("row_for_training:", rows_for_training)
    fold_count += 1
    
    X_train = X[rows_for_training]
    print("X_train:\n", X_train, "\n")
    y_train = y[rows_for_training]
    print("y_train:\n", np.matrix(y_train).T, "\n")
    
    print("row_for_testing:", rows_for_testing)
    X_test = X[rows_for_testing]
    print("X_test:\n", X_test, "\n")
    y_test = y[rows_for_testing]
    print("y_test:\n", np.matrix(y_test).T, "\n")
       

X:
 [[0 0]
 [1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]
 [6 6]
 [7 7]]
y:
 [[1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]] 

This is the # 1 fold of this stratification

row_for_training: [2 3 6 7]
X_train:
 [[2 2]
 [3 3]
 [6 6]
 [7 7]] 

y_train:
 [[1]
 [1]
 [0]
 [0]] 

row_for_testing: [0 1 4 5]
X_test:
 [[0 0]
 [1 1]
 [4 4]
 [5 5]] 

y_test:
 [[1]
 [1]
 [0]
 [0]] 

This is the # 2 fold of this stratification

row_for_training: [0 1 4 5]
X_train:
 [[0 0]
 [1 1]
 [4 4]
 [5 5]] 

y_train:
 [[1]
 [1]
 [0]
 [0]] 

row_for_testing: [2 3 6 7]
X_test:
 [[2 2]
 [3 3]
 [6 6]
 [7 7]] 

y_test:
 [[1]
 [1]
 [0]
 [0]] 



In [37]:
fold_by_3 = StratifiedKFold(n_splits = 3).split(X, y) 

fold_count = 1
for rows_for_training, rows_for_testing in fold_by_3:
    
    print("=====================")
    
    print("This is the #", fold_count, "fold of this stratification\n" )
    print("row_for_training:", rows_for_training)
    fold_count += 1
    
    X_train = X[rows_for_training]
    print("X_train:\n", X_train, "\n")
    y_train = y[rows_for_training]
    print("y_train:\n", np.matrix(y_train).T, "\n")
    
    print("row_for_testing:", rows_for_testing)
    X_test = X[rows_for_testing]
    print("X_test:\n", X_test, "\n")
    y_test = y[rows_for_testing]
    print("y_test:\n", np.matrix(y_test).T, "\n")

This is the # 1 fold of this stratification

row_for_training: [2 3 6 7]
X_train:
 [[2 2]
 [3 3]
 [6 6]
 [7 7]] 

y_train:
 [[1]
 [1]
 [0]
 [0]] 

row_for_testing: [0 1 4 5]
X_test:
 [[0 0]
 [1 1]
 [4 4]
 [5 5]] 

y_test:
 [[1]
 [1]
 [0]
 [0]] 

This is the # 2 fold of this stratification

row_for_training: [0 1 3 4 5 7]
X_train:
 [[0 0]
 [1 1]
 [3 3]
 [4 4]
 [5 5]
 [7 7]] 

y_train:
 [[1]
 [1]
 [1]
 [0]
 [0]
 [0]] 

row_for_testing: [2 6]
X_test:
 [[2 2]
 [6 6]] 

y_test:
 [[1]
 [0]] 

This is the # 3 fold of this stratification

row_for_training: [0 1 2 4 5 6]
X_train:
 [[0 0]
 [1 1]
 [2 2]
 [4 4]
 [5 5]
 [6 6]] 

y_train:
 [[1]
 [1]
 [1]
 [0]
 [0]
 [0]] 

row_for_testing: [3 7]
X_test:
 [[3 3]
 [7 7]] 

y_test:
 [[1]
 [0]] 

